name: nightly

on:
  schedule:
    - cron: '0 18 * * *'

concurrency:
  group: nightly
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  package:
    name: build package
    runs-on: [self-hosted, nebula]
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu1604
          - ubuntu1804
          - ubuntu2004
          # - centos6
          - centos7
          - centos8
    container:
      image: reg.vesoft-inc.com/vesoft/nebula-dev:${{ matrix.os }}
      credentials:
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    steps:
      - uses: webiny/action-post-run@2.0.1
        with:
          run: sh -c "find . -mindepth 1 -delete"
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.7'
      - name: package
        run: ./package/package.sh
      - name: output some vars
        id: vars
        env:
          SHA_EXT: sha256sum.txt
        run: |
          find pkg-build/cpack_output -type f \( -iname \*.deb -o -iname \*.rpm -o -iname \*.tar.gz \) -exec bash -c "sha256sum {} > {}.sha256sum.txt" \;
          subdir=$(date -u +%Y.%m.%d)
          echo "::set-output name=subdir::$subdir"
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}-nightly
          path: pkg-build/cpack_output
      - uses: ./.github/actions/upload-to-oss-action
        with:
          key-id: ${{ secrets.OSS_ID }}
          key-secret: ${{ secrets.OSS_SECRET }}
          endpoint: ${{ secrets.OSS_ENDPOINT }}
          bucket: nebula-graph-ent
          asset-path: pkg-build/cpack_output
          target-path: general/nebula-graph/nightly/${{ steps.vars.outputs.subdir }}

  docker:
    name: build docker image
    runs-on: [self-hosted, nebula]
    strategy:
      fail-fast: false
      matrix:
        service:
          - graphd
          - metad
          - storaged
          - tools
    steps:
      - uses: webiny/action-post-run@2.0.1
        with:
          run: sh -c "find . -mindepth 1 -delete"
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.${{ matrix.service }}
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.HARBOR_REGISTRY }}/vesoft-ent/nebula-${{ matrix.service }}:nightly
          push: true
