name: nightly

on:
  schedule:
    - cron: '0 18 * * *'

defaults:
  run:
    shell: bash

jobs:
  package:
    name: build package
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu1604
          - ubuntu1804
          - ubuntu2004
          # - centos6
          - centos7
          - centos8
    container:
      image: reg.vesoft-inc.com/vesoft/nebula-dev:${{ matrix.os }}
      credentials:
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    steps:
      - uses: webiny/action-post-run@2.0.1
        with:
          run: sh -c "rm -rf $(pwd)/*"
      - uses: actions/checkout@v2
      - name: package
        run: ./package/package.sh
      - name: output some vars
        id: vars
        env:
          SHA_EXT: sha256sum.txt
        run: |
          find pkg-build/cpack_output -type f \( -iname \*.deb -o -iname \*.rpm -o -iname \*.tar.gz \) -exec bash -c "sha256sum {} > {}.sha256sum.txt" \;
          subdir=$(date -u +%Y.%m.%d)
          echo "::set-output name=subdir::$subdir"
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}-nightly
          path: pkg-build/cpack_output
      - uses: ./.github/actions/upload-to-oss-action
        with:
          key-id: ${{ secrets.OSS_ID }}
          key-secret: ${{ secrets.OSS_SECRET }}
          endpoint: ${{ secrets.OSS_ENDPOINT }}
          bucket: nebula-graph-ent
          asset-path: pkg-build/cpack_output
          target-path: general/nebula-graph/nightly/${{ steps.vars.outputs.subdir }}

  docker:
    name: build docker image
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        service:
          - graphd
          - metad
          - storaged
          - tools
    steps:
      - uses: webiny/action-post-run@2.0.1
        with:
          run: sh -c "rm -rf ${{ github.workspace }}/*"
      - uses: actions/checkout@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
          repository: vesoft-ent/nebula-${{ matrix.service }}
          registry: ${{ secrets.HARBOR_REGISTRY }}
          path: .
          dockerfile: docker/Dockerfile.${{ matrix.service }}
          tags: nightly
          cache_froms: ${{ secrets.HARBOR_REGISTRY }}/vesoft/nebula-dev:centos7
          add_git_labels: true
