name: release

on:
  release:
    types:
      - published

defaults:
  run:
    shell: bash

jobs:
  package:
    name: build package
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu1604
          - ubuntu1804
          - ubuntu2004
          # - centos6
          - centos7
          - centos8
    container:
      image: reg.vesoft-inc.com/vesoft/nebula-dev:${{ matrix.os }}
      credentials:
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    env:
      BUILD_DIR: ./pkg-build
      CPACK_DIR: ./pkg-build/cpack_output
    steps:
      - uses: webiny/action-post-run@2.0.1
        with:
          run: sh -c "find . -mindepth 1 -delete"
      - uses: actions/checkout@v2
      - uses: ./.github/actions/tagname-action
        id: tag
      - name: package
        run: ./package/package.sh -b ${{ steps.tag.outputs.tag }}
      - name: output some vars
        run: |
          tar zcf ${{ env.CPACK_DIR }}/nebula-${{ steps.tag.outputs.tagnum }}.tar.gz --exclude=${{ env.BUILD_DIR }} ./*
          find ${{ env.CPACK_DIR }} -type f \( -iname \*.deb -o -iname \*.rpm \) -exec bash -c "sha256sum {} > {}.sha256sum.txt" \;
      - uses: ./.github/actions/upload-to-oss-action
        with:
          key-id: ${{ secrets.OSS_ID }}
          key-secret: ${{ secrets.OSS_SECRET }}
          endpoint: ${{ secrets.OSS_ENDPOINT }}
          bucket: nebula-graph-ent
          asset-path: ${{ env.CPACK_DIR }}
          target-path: general/nebula-graph/${{ steps.tag.outputs.tag }}

  docker_build:
    name: docker-build
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        service:
          - graphd
          - metad
          - storaged
          - tools
    steps:
      - uses: webiny/action-post-run@2.0.1
        with:
          run: sh -c "find . -mindepth 1 -delete"
      - uses: actions/checkout@v2
      - uses: ./.github/actions/tagname-action
        id: tagname
      - id: docker
        run: |
          majorver=$(git tag -l --sort=v:refname | tail -n1 | cut -f1 -d".")
          tag=""
          if [[ $majorver == ${{ steps.tagname.outputs.majorver }} ]]; then
            tag="vesoft/nebula-${{ matrix.service }}:latest"
          fi
          echo "::set-output name=tag::$tag"
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.${{ matrix.service }}
          tags: |
            ${{ secrets.HARBOR_REGISTRY }}/vesoft-ent/nebula-${{ matrix.service }}:${{ steps.tagname.outputs.tag }}
            ${{ secrets.HARBOR_REGISTRY }}/vesoft-ent/nebula-${{ matrix.service }}:latest
            ${{ steps.docker.outputs.tag }}
          push: true
          build-args: |
            BRANCH=${{ steps.tagname.outputs.tag }}
